# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hash_content',
            field=models.CharField(default=b'none', max_length=32),
        ),
    ]
