# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160228_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feed',
            field=models.ForeignKey(default=b'none', on_delete=django.db.models.deletion.CASCADE, to='main.Feed'),
        ),
    ]
